using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;


namespace VerifyWebApp.Models
{
    [Table("tblbatchverification")]
    public class BatchVerification
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public int ClientCode { get; set; }
        public int BatchID { get; set; }
        public string AssetNumber { get; set; } // Asset Numnber generated by Verify
        public int AssetIndex { get; set; }
        public int UserID { get; set; }
        [DataType(DataType.Date)]
        public DateTime LastUpdateTimeStamp { get; set; }
        public Double Longitude { get; set; }
        public Double Latitude { get; set; }
        public string Assetaddress { get; set; }


    }

   
}